# Generated by Django 6.0.5 on 2026-05-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ue',
            name='enseignant',
        ),
    ]
