# Generated by Django 6.0.5 on 2026-05-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_note_appreciation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='ue',
        ),
        migrations.AddField(
            model_name='examen',
            name='ressource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ressources'),
        ),
    ]
