# Generated by Django 6.0.5 on 2026-06-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_examen_ue_examen_ressource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressources',
            name='ue',
        ),
        migrations.AddField(
            model_name='ressources',
            name='ues',
            field=models.ManyToManyField(blank=True, related_name='ressources', to='app.ue'),
        ),
    ]
