# Generated by Django 6.0.6 on 2026-06-08 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_ressources_ue_ressources_ues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignants',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
